### PR TITLE
Fix #145, Use Google OAuth for App flow when generate OAuth token

### LINKED ISSUE #145: Alternative for Google OAuth out-of-band flow
As of October 3rd, MMM-Google Photos will probably be no longer working due to Google blocking OOB requests.

Are there any alternatives in the pipeline?

### PR DESCRIPTION
**Pull request by hermanho**
Fix #145
Use Google OAuth for App flow instead of OOB flow when generate OAuth token

ref: 
https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html

### CODE REVIEW

**Comment by aneaville** [comment]
hermano, I no longer am able to keep up with this repo. You seem to be the most logical candidate to take this over. Would you like me to transfer the repo to you?

**Comment by aaron-salamanca** [comment]
@hermanho thanks for your work on this!!

**Comment by hermanho** [comment]
> hermano, I no longer am able to keep up with this repo. You seem to be the most logical candidate to take this over. Would you like me to transfer the repo to you?

Yes, it's my pleasure

**Comment by aneaville** [comment]
> Yes, it's my pleasure

Great. I was unable to transfer to you because you have a repo with the same name. Let me know when you remove it or rename it and I will transfer to you.

**Comment by hermanho** [comment]
> > Yes, it's my pleasure
> 
> Great. I was unable to transfer to you because you have a repo with the same name. Let me know when you remove it or rename it and I will transfer to you.

Could you please retry?

**Comment by aneaville** [comment]
I get the following error when trying to transfer:
hermanho already has a repository in the aneaville/MMM-GooglePhotos network

**Comment by pedrolamas** [comment]
> hermanho already has a repository in the aneaville/MMM-GooglePhotos network

his fork, I guess! 🙂

**Comment by hermanho** [comment]
> I get the following error when trying to transfer:
> 
> hermanho already has a repository in the aneaville/MMM-GooglePhotos network

It's deleted now. Please see if it works.

**Pull request merged**
