### PR TITLE
Modified date label to be nostalgic-friendly (i.e. "Friday, 8 days ag…

### PR DESCRIPTION
**Pull request by adi-miller**
…o", "December, 4 years ago"), and moved stylign to css

### CODE REVIEW

**Comment by eouia** [comment]
Thanks always. 👍

**Comment by eouia** [comment]
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1

**Comment by adi-miller** [comment]
Wasn't MMM-GooglePhotos was just totally re-written?

**Comment by eouia** [comment]
You are right. But if you have an interest, take this over and change or modify as you want.

**Pull request merged**
