### PR TITLE
Fixing race condition for multiple albums.

### PR DESCRIPTION
**Pull request by philcali**
A couple of fixes here:

- Adds a `countDown` latch waiting for all albums to download before starting the broadcast
- Initializes the broadcast timer __once__. There were previously orphaned timers attempting to refresh the DOM.

### CODE REVIEW

**Comment by philcali** [comment]
To address issue #36

**Comment by eouia** [comment]
How to use it? Is there any change for using of current users?

**Comment by philcali** [comment]
No change to the current experience. All of the photos from the albums are cycled through instead of the last album to download :)

**Comment by eouia** [comment]
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1

**Pull request merged**
