### PR TITLE
Optionally specify multiple album Ids in an array

### PR DESCRIPTION
**Pull request by mdissel**

### CODE REVIEW

**Comment by eouia** [comment]
Thanks for your contribution. nice work.

**Comment by eouia** [comment]
I can't maintain this module any more.
Have you interest to take new ownership of this module?
https://forum.magicmirror.builders/topic/12779/wanted-new-ownership-of-modules?page=1

**Comment by mdissel** [comment]
Sorry, but i have no time to maintain this module. Thanks for your efforts!

**Comment by eouia** [comment]
Thanks for reply

**Pull request merged**
